### ISSUE TITLE
Cannot read properties of undefined (reading 'compiler')

### ISSUE THREAD

**Issue by devmdeniz** [wakatime/desktop#121]
I encountered this error while running ``yarn.cmd run build``.

I am waiting for you to get back to me as I cannot predict what extra information you may request.

<br><br>

![image](https://github.com/wakatime/desktop/assets/68655812/e7d9f10e-7699-47cc-b838-d5fa5ab8f297)

**Comment by alanhamlett** [comment]
This project isn't currently maintained. Please use https://GitHub.com/wakatime/macos-wakatime instead.
