### ISSUE TITLE
Dead Repo?

### ISSUE THREAD

**Issue by ElCapitanSponge** [wakatime/desktop#123]
I just stumbled across this repo and thought it would be cool to have a desktop application.

Alas upon seeing minimal contributions over the last few years and only one open issue, I was wondering if this is something that will still be developed? Or if development is even on the horizon.

**Comment by alanhamlett** [comment]
We have a desktop app for mac with [macos-wakatime](https://github.com/wakatime/macos-wakatime) and plan to revive this repo for Windows and Linux desktop apps in the future.
